export const defaultProducts = [
  {
    id: 1,
    name: "Product 1",
    description: "Description 1",
    price: 100,
    creationDate: new Date(),
  },
  {
    id: 2,
    name: "Product 2",
    description: "Description 2",
    price: 200,
    creationDate: new Date(),
  },
  {
    id: 3,
    name: "Product 3",
    description: "Description 3",
    price: 300,
    creationDate: new Date(),
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description 4",
    price: 400,
    creationDate: new Date(),
  },
  {
    id: 5,
    name: "Product 5",
    description: "Description 5",
    price: 100,
    creationDate: new Date(),
  },
  {
    id: 6,
    name: "Product 6",
    description: "Description 6",
    price: 200,
    creationDate: new Date(),
  },
  {
    id: 7,
    name: "Product 7",
    description: "Description 7",
    price: 300,
    creationDate: new Date(),
  },
  {
    id: 8,
    name: "Product 8",
    description: "Description 8",
    price: 400,
    creationDate: new Date(),
  },
  {
    id: 9,
    name: "Product 9",
    description: "Description 9",
    price: 500,
    creationDate: new Date(),
  },
  {
    id: 10,
    name: "Product 10",
    description: "Description 10",
    price: 600,
    creationDate: new Date(),
  },
  {
    id: 11,
    name: "Product 11",
    description: "Description 11",
    price: 700,
    creationDate: new Date(),
  },
  {
    id: 12,
    name: "Product 12",
    description: "Description 12",
    price: 800,
    creationDate: new Date(),
  },
];
